"""
UniGuide - University Degree Programme Knowledge Base

This is the Python mirror of flutter_app/lib/data/programme_repository.dart.
It is the single source of truth the backend uses for:
  1. Labelling the synthetic training dataset (synthetic_data_generator.py)
  2. Attaching admission requirements / careers / universities to each
     Random Forest prediction returned by /api/recommend and /api/programmes

Keep this file's programme titles, ids and codes in sync with the Dart
catalog so that a title predicted by the model always resolves to a real
programme card in the mobile app.
"""

from typing import Dict, List, TypedDict


class UniversityOffering(TypedDict):
    universityName: str
    universityType: str
    location: str
    latestCutoff: float
    previousCutoff: float
    kuccpsCode: str


class Programme(TypedDict):
    id: str
    code: str
    title: str
    faculty: str
    minMeanGrade: str
    averageCutoff: float
    clusterGroup: str
    clusterSubjects: List[str]
    minimumSubjectRequirements: Dict[str, str]
    description: str
    careerOpportunities: List[str]
    requiredSkills: List[str]
    professionalCertifications: List[str]
    offeringUniversities: List[UniversityOffering]
    durationYears: int


PROGRAMMES: List[Programme] = [
    {
        "id": "prog_mbchb",
        "code": "MED-101",
        "title": "Bachelor of Medicine and Bachelor of Surgery (MBChB)",
        "faculty": "School of Medicine and Health Sciences",
        "minMeanGrade": "A-",
        "averageCutoff": 43.5,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "English"],
        "minimumSubjectRequirements": {"Biology": "B+", "Chemistry": "B+", "Mathematics": "B", "English": "B"},
        "description": "Prepares professional physicians and surgeons through rigorous training in human anatomy, pathology, pharmacology, clinical rotations, and internal medicine.",
        "careerOpportunities": ["Medical Doctor", "General Physician", "Surgeon", "Clinical Researcher", "Medical Epidemiologist"],
        "requiredSkills": ["Clinical Diagnostics", "Patient Empathy", "Scientific Research", "Problem Solving", "Critical Thinking"],
        "professionalCertifications": ["Kenya Medical Practitioners and Dentists Council (KMPDC) Licensure", "Advanced Cardiac Life Support (ACLS)"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 43.8, "previousCutoff": 43.2, "kuccpsCode": "1070101"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 42.9, "previousCutoff": 42.5, "kuccpsCode": "1110101"},
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 42.4, "previousCutoff": 42.0, "kuccpsCode": "1020101"},
        ],
        "durationYears": 6,
    },
    {
        "id": "prog_pharm",
        "code": "PHA-102",
        "title": "Bachelor of Pharmacy (BPharm)",
        "faculty": "School of Pharmacy and Health Sciences",
        "minMeanGrade": "B+",
        "averageCutoff": 41.2,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "English"],
        "minimumSubjectRequirements": {"Chemistry": "B+", "Biology": "B+", "Mathematics": "B", "English": "B"},
        "description": "Comprehensive study of pharmaceutical chemistry, drug delivery systems, industrial pharmacy, clinical pharmacokinetics, and therapeutics.",
        "careerOpportunities": ["Pharmacist", "Clinical Pharmacologist", "Regulatory Affairs Specialist", "Pharmaceutical Formulator"],
        "requiredSkills": ["Chemical Analysis", "Pharmaceutical Formulation", "Attention to Detail", "Scientific Research"],
        "professionalCertifications": ["Pharmacy and Poisons Board (PPB) Licensure", "Good Clinical Practice (GCP) Certification"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.6, "previousCutoff": 41.1, "kuccpsCode": "1070103"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 40.5, "previousCutoff": 40.0, "kuccpsCode": "1110103"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_nursing",
        "code": "NUR-103",
        "title": "Bachelor of Science in Nursing",
        "faculty": "School of Nursing and Midwifery",
        "minMeanGrade": "B",
        "averageCutoff": 38.6,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "English"],
        "minimumSubjectRequirements": {"Biology": "B", "Chemistry": "B", "English": "B", "Mathematics": "C+"},
        "description": "Focuses on acute patient care, community health nursing, midwifery, healthcare leadership, and evidence-based clinical practices.",
        "careerOpportunities": ["Registered Nurse", "Clinical Care Specialist", "Public Health Officer", "Nurse Educator"],
        "requiredSkills": ["Patient Empathy", "Clinical Nursing Procedures", "Communication", "Team Collaboration"],
        "professionalCertifications": ["Nursing Council of Kenya (NCK) Practicing License", "Basic Life Support (BLS)"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 39.2, "previousCutoff": 38.7, "kuccpsCode": "1070105"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 38.4, "previousCutoff": 38.0, "kuccpsCode": "1110105"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_ics",
        "code": "ICS-201",
        "title": "Bachelor of Science in Informatics and Computer Science",
        "faculty": "School of Computing and Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 39.5,
        "clusterGroup": "Cluster 2: Computing & IT",
        "clusterSubjects": ["Mathematics", "Physics", "English", "Chemistry"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+"},
        "description": "Rigorous curriculum covering algorithm design, artificial intelligence, software engineering, cloud computing, distributed databases, and cybersecurity.",
        "careerOpportunities": ["Software Engineer", "AI Specialist", "Data Scientist", "Cloud Solutions Architect", "Systems Architect"],
        "requiredSkills": ["Python Coding", "System Architecture", "Algorithms", "Mathematical Analysis", "Problem Solving"],
        "professionalCertifications": ["AWS Certified Solutions Architect", "Google Professional Machine Learning Engineer"],
        "offeringUniversities": [
            {"universityName": "Strathmore University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 39.8, "previousCutoff": 39.2, "kuccpsCode": "1240101"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.2, "previousCutoff": 40.8, "kuccpsCode": "1070201"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 40.1, "previousCutoff": 39.6, "kuccpsCode": "1080201"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_se",
        "code": "SE-202",
        "title": "Bachelor of Science in Software Engineering",
        "faculty": "School of Computing and Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 38.6,
        "clusterGroup": "Cluster 2: Computing & IT",
        "clusterSubjects": ["Mathematics", "Physics", "English", "Chemistry"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+"},
        "description": "Specialized focus on the enterprise software development lifecycle, DevOps, microservices architecture, software testing, and agile delivery.",
        "careerOpportunities": ["Full-Stack Developer", "DevOps Engineer", "Mobile Application Developer", "Software Quality Assurance Lead"],
        "requiredSkills": ["Python Coding", "OOP Principles", "CI/CD Pipelines", "Version Control (Git)", "Team Collaboration"],
        "professionalCertifications": ["Certified ScrumMaster (CSM)", "Microsoft Certified: DevOps Engineer Expert"],
        "offeringUniversities": [
            {"universityName": "Strathmore University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 38.8, "previousCutoff": 38.2, "kuccpsCode": "1240102"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 39.2, "previousCutoff": 38.8, "kuccpsCode": "1080202"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_bbit",
        "code": "BBIT-203",
        "title": "Bachelor of Science in Business Information Technology (BBIT)",
        "faculty": "School of Computing and Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 35.4,
        "clusterGroup": "Cluster 2: Computing & IT",
        "clusterSubjects": ["Mathematics", "English", "Physics", "Business Studies"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "English": "C+"},
        "description": "Bridges modern computational technology with corporate strategic management, covering ERP systems, business intelligence, IT project governance, and database administration.",
        "careerOpportunities": ["Business Systems Analyst", "IT Project Manager", "ERP Consultant", "Database Administrator"],
        "requiredSkills": ["Business Intelligence", "SQL Databases", "Strategic IT Management", "Communication"],
        "professionalCertifications": ["Certified Information Systems Auditor (CISA)", "Project Management Professional (PMP)"],
        "offeringUniversities": [
            {"universityName": "Strathmore University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 35.6, "previousCutoff": 35.0, "kuccpsCode": "1240103"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 36.1, "previousCutoff": 35.8, "kuccpsCode": "1080203"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_eee",
        "code": "ENG-301",
        "title": "Bachelor of Science in Electrical and Electronic Engineering",
        "faculty": "School of Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 41.5,
        "clusterGroup": "Cluster 5: Engineering & Technology",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "English"],
        "minimumSubjectRequirements": {"Mathematics": "B", "Physics": "B", "Chemistry": "C+"},
        "description": "Instruction in electric power grids, telecommunication networks, control systems, microelectronics, embedded processors, and renewable energy conversion.",
        "careerOpportunities": ["Electrical Power Engineer", "Telecommunications Engineer", "Embedded Systems Developer", "Renewable Energy Consultant"],
        "requiredSkills": ["Mathematical Analysis", "Circuit Simulation", "CAD Modeling", "Critical Thinking"],
        "professionalCertifications": ["Engineers Board of Kenya (EBK) Registration", "Certified Energy Manager (CEM)"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 42.1, "previousCutoff": 41.6, "kuccpsCode": "1070501"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 41.2, "previousCutoff": 40.8, "kuccpsCode": "1080501"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_civil",
        "code": "ENG-302",
        "title": "Bachelor of Science in Civil Engineering",
        "faculty": "School of Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 40.8,
        "clusterGroup": "Cluster 5: Engineering & Technology",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "English"],
        "minimumSubjectRequirements": {"Mathematics": "B", "Physics": "B", "Chemistry": "C+"},
        "description": "Focuses on structural design, geotechnical mechanics, transportation systems, highway engineering, and sustainable urban water infrastructure.",
        "careerOpportunities": ["Structural Engineer", "Civil Project Engineer", "Geotechnical Engineer", "Urban Infrastructure Planner"],
        "requiredSkills": ["CAD Modeling", "Structural Analysis", "Mathematical Analysis", "Project Management"],
        "professionalCertifications": ["Engineers Board of Kenya (EBK) Graduate Engineer", "Autodesk AutoCAD / Civil 3D Certified Professional"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.4, "previousCutoff": 40.9, "kuccpsCode": "1070502"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 40.4, "previousCutoff": 40.0, "kuccpsCode": "1080502"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_law",
        "code": "LAW-401",
        "title": "Bachelor of Laws (LLB)",
        "faculty": "Strathmore Law School",
        "minMeanGrade": "B",
        "averageCutoff": 40.2,
        "clusterGroup": "Cluster 14: Law & Legal Studies",
        "clusterSubjects": ["English", "Kiswahili", "Mathematics", "History"],
        "minimumSubjectRequirements": {"English": "B", "Kiswahili": "B"},
        "description": "Comprehensive legal education covering constitutional jurisprudence, international trade law, corporate governance, human rights, intellectual property, and litigation.",
        "careerOpportunities": ["Advocate of the High Court of Kenya", "Corporate Legal Counsel", "Judicial Research Officer", "Policy Analyst & Legislative Drafter"],
        "requiredSkills": ["Legal Research & Writing", "Debate & Persuasive Advocacy", "Critical Thinking", "Attention to Detail"],
        "professionalCertifications": ["Kenya School of Law (ATP Post-Graduate Diploma)", "Law Society of Kenya (LSK) Membership"],
        "offeringUniversities": [
            {"universityName": "Strathmore University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 40.5, "previousCutoff": 39.8, "kuccpsCode": "1240401"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.0, "previousCutoff": 40.4, "kuccpsCode": "1070401"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_actuarial",
        "code": "ACT-501",
        "title": "Bachelor of Science in Actuarial Science",
        "faculty": "School of Mathematics and Financial Sciences",
        "minMeanGrade": "B",
        "averageCutoff": 40.9,
        "clusterGroup": "Cluster 6: Business, Finance & Mathematics",
        "clusterSubjects": ["Mathematics", "English", "Physics", "Chemistry"],
        "minimumSubjectRequirements": {"Mathematics": "A-", "English": "B"},
        "description": "Mathematical and statistical modeling of financial risk, life contingencies, actuarial mathematics, asset-liability valuation, and insurance mathematics.",
        "careerOpportunities": ["Actuarial Analyst", "Risk Management Consultant", "Pension Fund Strategist", "Investment Banker"],
        "requiredSkills": ["Mathematical Analysis", "Statistical Modeling", "Problem Solving", "Critical Thinking"],
        "professionalCertifications": ["Institute and Faculty of Actuaries (IFoA) Exams (CM1, CB1, CS1)", "Society of Actuaries (SOA) Professional Series"],
        "offeringUniversities": [
            {"universityName": "Strathmore University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 41.0, "previousCutoff": 40.5, "kuccpsCode": "1240501"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.4, "previousCutoff": 41.0, "kuccpsCode": "1070505"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_bcom",
        "code": "BUS-502",
        "title": "Bachelor of Commerce (BCom) - Finance & Accounting",
        "faculty": "Strathmore University Business School",
        "minMeanGrade": "C+",
        "averageCutoff": 34.8,
        "clusterGroup": "Cluster 7: Business & Economics",
        "clusterSubjects": ["Mathematics", "English", "Business Studies", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "English": "C+"},
        "description": "Equips students with analytical tools in corporate finance, managerial accounting, banking systems, financial reporting, and capital markets investment.",
        "careerOpportunities": ["Financial Analyst", "Chartered Accountant", "Internal Auditor", "Investment Banker"],
        "requiredSkills": ["Financial Modeling", "Attention to Detail", "Communication", "Leadership"],
        "professionalCertifications": ["Certified Public Accountants of Kenya (CPA-K)", "Chartered Financial Analyst (CFA) Level 1"],
        "offeringUniversities": [
            {"universityName": "Strathmore University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 35.2, "previousCutoff": 34.5, "kuccpsCode": "1240502"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 35.8, "previousCutoff": 35.1, "kuccpsCode": "1070508"},
        ],
        "durationYears": 4,
    },
    # --- The 10 entries below were added from KUCCPS's official 2025/2026
    # degree programmes list (statics.kuccps.net/uploads/globalFiles/
    # DEGREE_PROGRAMMES_2025.pdf) - real programme codes, subject
    # requirements, and per-university cutoff points (2023/2022 COP), not
    # estimated. Career/skill/certification fields are standard, well-known
    # facts about each profession in Kenya (real regulators: BORAQS, EBK,
    # KMPDC, KVB, MCK, KNDI), not KUCCPS-sourced data.
    {
        "id": "prog_dental",
        "code": "DEN-104",
        "title": "Bachelor of Dental Surgery (BDS)",
        "faculty": "School of Dental Sciences",
        "minMeanGrade": "A-",
        "averageCutoff": 44.6,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "English"],
        "minimumSubjectRequirements": {"Biology": "B", "Chemistry": "B", "Mathematics": "B", "English": "B"},
        "description": "Trains dental surgeons in oral diagnostics, restorative dentistry, oral surgery, orthodontics, and periodontology.",
        "careerOpportunities": ["Dentist", "Oral Surgeon", "Orthodontist", "Dental Public Health Officer"],
        "requiredSkills": ["Clinical Dexterity", "Patient Care", "Diagnostic Imaging Interpretation", "Attention to Detail"],
        "professionalCertifications": ["Kenya Medical Practitioners and Dentists Council (KMPDC) Licensure", "Basic Life Support (BLS)"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 44.75, "previousCutoff": 44.334, "kuccpsCode": "1263128"},
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 44.502, "previousCutoff": 44.07, "kuccpsCode": "1253128"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_vet",
        "code": "VET-105",
        "title": "Bachelor of Veterinary Medicine (BVM)",
        "faculty": "Faculty of Veterinary Medicine",
        "minMeanGrade": "B",
        "averageCutoff": 38.0,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "Physics"],
        "minimumSubjectRequirements": {"Biology": "C+", "Chemistry": "C+", "Mathematics": "C"},
        "description": "Covers animal anatomy and physiology, veterinary surgery, epidemiology, livestock health management, and wildlife veterinary practice.",
        "careerOpportunities": ["Veterinary Doctor", "Livestock Health Officer", "Wildlife Veterinarian", "Veterinary Public Health Officer"],
        "requiredSkills": ["Animal Clinical Diagnostics", "Surgical Procedures", "Epidemiology", "Communication"],
        "professionalCertifications": ["Kenya Veterinary Board (KVB) Licensure"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 37.747, "previousCutoff": 39.091, "kuccpsCode": "1263130"},
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 38.317, "previousCutoff": 38.443, "kuccpsCode": "1057130"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_nutrition",
        "code": "NUT-106",
        "title": "Bachelor of Science in Food, Nutrition and Dietetics",
        "faculty": "School of Public Health and Applied Human Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 28.9,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "Geography"],
        "minimumSubjectRequirements": {"Biology": "C", "Chemistry": "C", "Mathematics": "C", "English": "C"},
        "description": "Studies clinical nutrition, dietetic therapy, food science, public health nutrition, and community nutrition programme design.",
        "careerOpportunities": ["Clinical Dietitian", "Public Health Nutritionist", "Food Service Manager", "Community Nutrition Officer"],
        "requiredSkills": ["Diet Planning", "Clinical Nutritional Assessment", "Public Health Communication", "Food Science"],
        "professionalCertifications": ["Kenya Nutritionists and Dietitians Institute (KNDI) Licensure"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 31.104, "previousCutoff": 33.75, "kuccpsCode": "1263190"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 30.185, "previousCutoff": 33.006, "kuccpsCode": "1111190"},
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 25.471, "previousCutoff": 29.18, "kuccpsCode": "1057190"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_mech",
        "code": "MECH-303",
        "title": "Bachelor of Science in Mechanical Engineering",
        "faculty": "School of Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 41.5,
        "clusterGroup": "Cluster 5: Engineering & Technology",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "English"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+", "Chemistry": "C+", "English": "C+"},
        "description": "Covers thermodynamics, machine design, manufacturing systems, fluid mechanics, and mechatronics for industrial and automotive applications.",
        "careerOpportunities": ["Mechanical Engineer", "Automotive Engineer", "HVAC Engineer", "Manufacturing/Production Engineer"],
        "requiredSkills": ["CAD/CAM Modeling", "Thermodynamics Analysis", "Machine Design", "Problem Solving"],
        "professionalCertifications": ["Engineers Board of Kenya (EBK) Registration", "Certified SolidWorks Professional"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.835, "previousCutoff": 41.321, "kuccpsCode": "1263118"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 41.45, "previousCutoff": 41.449, "kuccpsCode": "1249118"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.109, "previousCutoff": 41.033, "kuccpsCode": "1111118"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_arch",
        "code": "ARC-304",
        "title": "Bachelor of Architecture",
        "faculty": "School of the Built Environment",
        "minMeanGrade": "C+",
        "averageCutoff": 41.8,
        "clusterGroup": "Cluster 4: Built Environment & Geosciences",
        "clusterSubjects": ["Mathematics", "Physics", "English", "Kiswahili"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+", "English": "C+"},
        "description": "Studies architectural design theory, building technology, urban design, construction materials, and professional practice management.",
        "careerOpportunities": ["Architect", "Urban Designer", "Interior Architect", "Construction Project Consultant"],
        "requiredSkills": ["CAD Modeling", "Spatial Design", "Building Codes Knowledge", "Sketching & Visualization"],
        "professionalCertifications": ["Board of Registration of Architects and Quantity Surveyors (BORAQS) Kenya", "Autodesk Revit Certified Professional"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 42.99, "previousCutoff": 43.794, "kuccpsCode": "1263102"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.494, "previousCutoff": 42.407, "kuccpsCode": "1111102"},
            {"universityName": "Technical University of Kenya", "universityType": "Public", "location": "Nairobi", "latestCutoff": 41.035, "previousCutoff": 41.962, "kuccpsCode": "1112102"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_qs",
        "code": "QS-305",
        "title": "Bachelor of Quantity Surveying",
        "faculty": "School of the Built Environment",
        "minMeanGrade": "C+",
        "averageCutoff": 39.5,
        "clusterGroup": "Cluster 4: Built Environment & Geosciences",
        "clusterSubjects": ["Mathematics", "Physics", "English", "Kiswahili"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+", "English": "C+"},
        "description": "Focuses on construction cost estimation, contract administration, bills of quantities preparation, and construction economics.",
        "careerOpportunities": ["Quantity Surveyor", "Construction Cost Consultant", "Contracts Manager", "Project Estimator"],
        "requiredSkills": ["Cost Estimation", "Contract Administration", "Bill of Quantities Preparation", "Construction Economics"],
        "professionalCertifications": ["Board of Registration of Architects and Quantity Surveyors (BORAQS) Kenya", "Institute of Quantity Surveyors of Kenya (IQSK) Membership"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 40.232, "previousCutoff": 40.993, "kuccpsCode": "1263103"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 39.763, "previousCutoff": 41.641, "kuccpsCode": "1249103"},
            {"universityName": "Technical University of Kenya", "universityType": "Public", "location": "Nairobi", "latestCutoff": 38.424, "previousCutoff": 40.533, "kuccpsCode": "1112103"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_math",
        "code": "MATH-503",
        "title": "Bachelor of Science in Mathematics",
        "faculty": "School of Mathematics and Financial Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 28.6,
        "clusterGroup": "Cluster 6: Business, Finance & Mathematics",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C+"},
        "description": "Pure and applied mathematics, statistics, and mathematical modeling, preparing graduates for data-driven analytical careers.",
        "careerOpportunities": ["Data Analyst", "Statistician", "Operations Research Analyst", "Mathematics Educator"],
        "requiredSkills": ["Mathematical Modeling", "Statistical Analysis", "Problem Solving", "Programming (R/Python)"],
        "professionalCertifications": ["SAS Certified Statistical Business Analyst"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 32.945, "previousCutoff": 32.487, "kuccpsCode": "1263109"},
            {"universityName": "Technical University of Kenya", "universityType": "Public", "location": "Nairobi", "latestCutoff": 24.252, "previousCutoff": 26.695, "kuccpsCode": "1112109"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_econ",
        "code": "ECON-504",
        "title": "Bachelor of Economics",
        "faculty": "School of Economics",
        "minMeanGrade": "C+",
        "averageCutoff": 26.5,
        "clusterGroup": "Cluster 7: Business & Economics",
        "clusterSubjects": ["Mathematics", "English", "Kiswahili", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "English": "C"},
        "description": "Analyzes microeconomic and macroeconomic theory, econometrics, development economics, and public policy analysis.",
        "careerOpportunities": ["Economist", "Policy Analyst", "Financial Consultant", "Market Research Analyst"],
        "requiredSkills": ["Econometric Modeling", "Data Analysis", "Policy Research", "Communication"],
        "professionalCertifications": ["Chartered Financial Analyst (CFA) Level 1", "Kenya Institute of Bankers (KIB) Certification"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 26.096, "previousCutoff": 30.453, "kuccpsCode": "1263146"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 26.413, "previousCutoff": 24.1, "kuccpsCode": "1111146"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 27.073, "previousCutoff": 22.977, "kuccpsCode": "1249146"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_jmc",
        "code": "JMC-601",
        "title": "Bachelor of Arts in Journalism and Mass Communication",
        "faculty": "School of Journalism and Mass Communication",
        "minMeanGrade": "C+",
        "averageCutoff": 29.4,
        "clusterGroup": "Cluster 3: Communication, Media & Social Sciences",
        "clusterSubjects": ["English", "Kiswahili", "History", "Geography"],
        "minimumSubjectRequirements": {"English": "C+", "Kiswahili": "C+"},
        "description": "Trains journalists and communicators in news writing, broadcast production, digital media, public relations, and media law and ethics.",
        "careerOpportunities": ["Journalist", "Broadcast Presenter", "Public Relations Officer", "Digital Content Strategist"],
        "requiredSkills": ["News Writing & Reporting", "Media Production", "Research", "Communication"],
        "professionalCertifications": ["Media Council of Kenya (MCK) Accreditation"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 29.254, "previousCutoff": 34.056, "kuccpsCode": "1263181"},
            {"universityName": "Technical University of Mombasa", "universityType": "Public", "location": "Mombasa", "latestCutoff": 29.885, "previousCutoff": 32.201, "kuccpsCode": "1063181"},
            {"universityName": "Chuka University", "universityType": "Public", "location": "Chuka", "latestCutoff": 29.127, "previousCutoff": 32.408, "kuccpsCode": "1105385"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_agri",
        "code": "AGR-701",
        "title": "Bachelor of Science in Agriculture",
        "faculty": "Faculty of Agriculture",
        "minMeanGrade": "C+",
        "averageCutoff": 15.9,
        "clusterGroup": "Cluster 8: Agriculture & Natural Resources",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "Geography"],
        "minimumSubjectRequirements": {"Biology": "C+", "Chemistry": "C", "Mathematics": "C"},
        "description": "Covers crop and soil science, agricultural economics, livestock production, and agribusiness management for sustainable farming systems.",
        "careerOpportunities": ["Agricultural Officer", "Agronomist", "Farm Manager", "Agricultural Extension Officer"],
        "requiredSkills": ["Crop & Soil Science", "Agribusiness Planning", "Field Research", "Sustainable Farming Practices"],
        "professionalCertifications": ["Kenya Agricultural and Livestock Research Organization (KALRO) Affiliation", "Certified Crop Advisor"],
        "offeringUniversities": [
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 15.864, "previousCutoff": 23.701, "kuccpsCode": "1057122"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 15.864, "previousCutoff": 22.782, "kuccpsCode": "1263122"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 15.864, "previousCutoff": 23.704, "kuccpsCode": "1111122"},
        ],
        "durationYears": 4,
    },
    # --- The 19 entries below were added from the same official KUCCPS
    # 2025/2026 degree programmes list as the batch above. Where a
    # programme is only genuinely offered by 1-2 universities in that
    # source (Hospitality Management, Real Estate Management, International
    # Business Management, Urban and Regional Planning), only those real
    # entries are listed rather than padding to 3-4 with invented ones.
    {
        "id": "prog_indchem",
        "code": "SCI-801",
        "title": "Bachelor of Science in Industrial Chemistry",
        "faculty": "School of Pure and Applied Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 26.0,
        "clusterGroup": "Cluster 9: Pure & Applied Sciences",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "English"],
        "minimumSubjectRequirements": {"Mathematics": "C", "Physics": "C", "Chemistry": "C+"},
        "description": "Covers industrial and analytical chemistry, chemical process technology, and quality control for manufacturing and research laboratories.",
        "careerOpportunities": ["Industrial Chemist", "Quality Control Analyst", "Chemical Process Technologist", "Research Chemist"],
        "requiredSkills": ["Chemical Analysis", "Laboratory Research", "Process Optimization", "Attention to Detail"],
        "professionalCertifications": ["Institute of Certified Public Analysts of Kenya", "Chemical Society of Kenya Membership"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 27.458, "previousCutoff": 31.98, "kuccpsCode": "1263108"},
            {"universityName": "Maseno University", "universityType": "Public", "location": "Kisumu", "latestCutoff": 25.535, "previousCutoff": 23.851, "kuccpsCode": "1229108"},
            {"universityName": "Masinde Muliro University of Science and Technology", "universityType": "Public", "location": "Kakamega", "latestCutoff": 25.036, "previousCutoff": 15.982, "kuccpsCode": "1082108"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_micro",
        "code": "SCI-802",
        "title": "Bachelor of Science in Microbiology",
        "faculty": "School of Pure and Applied Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 25.8,
        "clusterGroup": "Cluster 9: Pure & Applied Sciences",
        "clusterSubjects": ["Mathematics", "Biology", "Chemistry", "English"],
        "minimumSubjectRequirements": {"Mathematics": "C", "Biology": "C+", "Chemistry": "C"},
        "description": "Studies microorganisms, immunology, and microbial genetics, with applications in clinical diagnostics, food safety, and industrial biotechnology.",
        "careerOpportunities": ["Microbiologist", "Clinical Laboratory Scientist", "Quality Assurance Analyst", "Research Microbiologist"],
        "requiredSkills": ["Microbial Culturing", "Laboratory Research", "Data Analysis", "Attention to Detail"],
        "professionalCertifications": ["Kenya Medical Laboratory Technicians and Technologists Board (KMLTTB) Licensure"],
        "offeringUniversities": [
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 26.794, "previousCutoff": 16.974, "kuccpsCode": "1253123"},
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 25.46, "previousCutoff": 25.937, "kuccpsCode": "1111123"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 25.28, "previousCutoff": 26.199, "kuccpsCode": "1249123"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_foodsci",
        "code": "SCI-803",
        "title": "Bachelor of Science in Food Science and Technology",
        "faculty": "Faculty of Agriculture",
        "minMeanGrade": "C+",
        "averageCutoff": 23.8,
        "clusterGroup": "Cluster 9: Pure & Applied Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "Geography"],
        "minimumSubjectRequirements": {"Biology": "C", "Chemistry": "C", "Mathematics": "C"},
        "description": "Covers food processing, preservation, product development, and food safety regulation from raw material to consumer.",
        "careerOpportunities": ["Food Technologist", "Quality Assurance Manager", "Product Development Scientist", "Food Safety Officer"],
        "requiredSkills": ["Food Processing", "Quality Control", "Laboratory Research", "Regulatory Compliance"],
        "professionalCertifications": ["Kenya Bureau of Standards (KEBS) Certification", "HACCP Certification"],
        "offeringUniversities": [
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 30.855, "previousCutoff": 33.076, "kuccpsCode": "1249124"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 23.85, "previousCutoff": 32.155, "kuccpsCode": "1263124"},
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 24.645, "previousCutoff": 17.043, "kuccpsCode": "1057124"},
            {"universityName": "Dedan Kimathi University of Technology", "universityType": "Public", "location": "Nyeri", "latestCutoff": 15.864, "previousCutoff": 17.043, "kuccpsCode": "1173124"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_stats",
        "code": "MATH-504",
        "title": "Bachelor of Science in Statistics",
        "faculty": "School of Mathematics and Financial Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 30.6,
        "clusterGroup": "Cluster 6: Business, Finance & Mathematics",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C+"},
        "description": "Focuses on probability theory, statistical inference, sampling design, and applied data analysis for research and industry.",
        "careerOpportunities": ["Statistician", "Data Analyst", "Research Analyst", "Biostatistician"],
        "requiredSkills": ["Statistical Modeling", "Data Analysis", "Programming (R/Python)", "Research Design"],
        "professionalCertifications": ["Kenya National Bureau of Statistics Affiliation", "SAS Certified Statistical Business Analyst"],
        "offeringUniversities": [
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 35.192, "previousCutoff": 33.673, "kuccpsCode": "1263163"},
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 30.147, "previousCutoff": 27.899, "kuccpsCode": "1249163"},
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 26.311, "previousCutoff": 19.914, "kuccpsCode": "1057163"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_edsci",
        "code": "EDU-901",
        "title": "Bachelor of Education (Science)",
        "faculty": "School of Education",
        "minMeanGrade": "B",
        "averageCutoff": 35.8,
        "clusterGroup": "Cluster 10: Education & Teacher Training",
        "clusterSubjects": ["Mathematics", "Biology", "Physics", "Chemistry"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Biology": "C+"},
        "description": "Trains secondary school science teachers, combining pedagogy and curriculum studies with two teaching subjects from Mathematics, Biology, Physics, or Chemistry.",
        "careerOpportunities": ["Secondary School Science Teacher", "Curriculum Developer", "Education Officer", "STEM Instructor"],
        "requiredSkills": ["Pedagogy & Lesson Planning", "Subject Mastery", "Classroom Management", "Communication"],
        "professionalCertifications": ["Teachers Service Commission (TSC) Registration"],
        "offeringUniversities": [
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 37.208, "previousCutoff": 37.778, "kuccpsCode": "1111137"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 36.127, "previousCutoff": 37.073, "kuccpsCode": "1263137"},
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 35.289, "previousCutoff": 35.282, "kuccpsCode": "1057137"},
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 34.603, "previousCutoff": 35.434, "kuccpsCode": "1253137"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_edarts",
        "code": "EDU-902",
        "title": "Bachelor of Education (Arts)",
        "faculty": "School of Education",
        "minMeanGrade": "C+",
        "averageCutoff": 32.1,
        "clusterGroup": "Cluster 10: Education & Teacher Training",
        "clusterSubjects": ["English", "Kiswahili", "Mathematics", "Geography"],
        "minimumSubjectRequirements": {"English": "C+", "Kiswahili": "C+"},
        "description": "Trains secondary school humanities teachers, combining pedagogy and curriculum studies with two teaching subjects from Languages, Humanities, or Business Studies.",
        "careerOpportunities": ["Secondary School Humanities Teacher", "Curriculum Developer", "Education Officer", "Guidance Counselor"],
        "requiredSkills": ["Pedagogy & Lesson Planning", "Communication", "Classroom Management", "Curriculum Design"],
        "professionalCertifications": ["Teachers Service Commission (TSC) Registration"],
        "offeringUniversities": [
            {"universityName": "Kenyatta University", "universityType": "Public", "location": "Nairobi", "latestCutoff": 33.556, "previousCutoff": 34.725, "kuccpsCode": "1111135"},
            {"universityName": "University of Nairobi", "universityType": "Public", "location": "Nairobi", "latestCutoff": 32.421, "previousCutoff": 33.663, "kuccpsCode": "1263135"},
            {"universityName": "Egerton University", "universityType": "Public", "location": "Njoro", "latestCutoff": 32.306, "previousCutoff": 32.486, "kuccpsCode": "1057135"},
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 30.04, "previousCutoff": 30.707, "kuccpsCode": "1253135"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_pubhealth",
        "code": "HLT-107",
        "title": "Bachelor of Science in Public Health",
        "faculty": "School of Public Health and Applied Human Sciences",
        "minMeanGrade": "B",
        "averageCutoff": 30.9,
        "clusterGroup": "Cluster 1: Medicine & Health Sciences",
        "clusterSubjects": ["Biology", "Chemistry", "Mathematics", "English"],
        "minimumSubjectRequirements": {"Biology": "C+", "Chemistry": "C+", "Mathematics": "C+", "English": "C+"},
        "description": "Covers epidemiology, environmental health, health promotion, and disease surveillance for community and population-level health.",
        "careerOpportunities": ["Public Health Officer", "Epidemiologist", "Health Promotion Officer", "Environmental Health Officer"],
        "requiredSkills": ["Epidemiological Surveillance", "Health Education", "Community Outreach", "Data Analysis"],
        "professionalCertifications": ["Public Health Officers and Technicians Council Licensure"],
        "offeringUniversities": [
            {"universityName": "Maseno University", "universityType": "Public", "location": "Kisumu", "latestCutoff": 33.436, "previousCutoff": 34.339, "kuccpsCode": "1229732"},
            {"universityName": "Kisii University", "universityType": "Public", "location": "Kisii", "latestCutoff": 31.45, "previousCutoff": 32.151, "kuccpsCode": "1087732"},
            {"universityName": "University of Kabianga", "universityType": "Public", "location": "Kericho", "latestCutoff": 29.664, "previousCutoff": 30.613, "kuccpsCode": "1118732"},
            {"universityName": "South Eastern Kenya University", "universityType": "Public", "location": "Kitui", "latestCutoff": 29.179, "previousCutoff": 27.342, "kuccpsCode": "1166732"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_socio",
        "code": "SOC-101",
        "title": "Bachelor of Arts in Sociology",
        "faculty": "School of Humanities and Social Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 22.4,
        "clusterGroup": "Cluster 3: Communication, Media & Social Sciences",
        "clusterSubjects": ["English", "Kiswahili", "History", "Geography"],
        "minimumSubjectRequirements": {"English": "C+"},
        "description": "Studies social structures, human behavior, and community dynamics, preparing graduates for research and development-sector work.",
        "careerOpportunities": ["Social Researcher", "Community Development Officer", "Policy Analyst", "NGO Programme Officer"],
        "requiredSkills": ["Social Research Methods", "Community Engagement", "Report Writing", "Critical Analysis"],
        "professionalCertifications": [],
        "offeringUniversities": [
            {"universityName": "Chuka University", "universityType": "Public", "location": "Chuka", "latestCutoff": 22.449, "previousCutoff": 24.374, "kuccpsCode": "1105806"},
            {"universityName": "Rongo University", "universityType": "Public", "location": "Rongo", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1073806"},
            {"universityName": "Pwani University", "universityType": "Public", "location": "Kilifi", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1117806"},
            {"universityName": "Maasai Mara University", "universityType": "Public", "location": "Narok", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1165806"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_socialwork",
        "code": "SOC-102",
        "title": "Bachelor of Social Work",
        "faculty": "School of Humanities and Social Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 22.4,
        "clusterGroup": "Cluster 3: Communication, Media & Social Sciences",
        "clusterSubjects": ["English", "Kiswahili", "History", "Geography"],
        "minimumSubjectRequirements": {"English": "C+"},
        "description": "Prepares professional social workers in case management, child protection, community development, and welfare policy.",
        "careerOpportunities": ["Social Worker", "Child Protection Officer", "Community Development Officer", "Case Manager"],
        "requiredSkills": ["Case Management", "Counseling", "Community Engagement", "Empathy & Ethics"],
        "professionalCertifications": ["Kenya National Association of Social Workers (KNASW) Membership"],
        "offeringUniversities": [
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 22.449, "previousCutoff": 28.081, "kuccpsCode": "1253144"},
            {"universityName": "South Eastern Kenya University", "universityType": "Public", "location": "Kitui", "latestCutoff": 22.449, "previousCutoff": 24.682, "kuccpsCode": "1166144"},
            {"universityName": "Masinde Muliro University of Science and Technology", "universityType": "Public", "location": "Kakamega", "latestCutoff": 22.449, "previousCutoff": 25.199, "kuccpsCode": "1082145"},
            {"universityName": "Catholic University of Eastern Africa", "universityType": "Private", "location": "Nairobi", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1480144"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_counsel",
        "code": "SOC-103",
        "title": "Bachelor of Arts in Counseling Psychology",
        "faculty": "School of Humanities and Social Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 23.0,
        "clusterGroup": "Cluster 3: Communication, Media & Social Sciences",
        "clusterSubjects": ["English", "Kiswahili", "History", "Geography"],
        "minimumSubjectRequirements": {"English": "C+"},
        "description": "Covers counseling theory, human development, and psychological assessment for mental health and guidance-and-counseling roles.",
        "careerOpportunities": ["Counseling Psychologist", "Guidance & Counseling Officer", "Mental Health Counselor", "HR Wellness Officer"],
        "requiredSkills": ["Active Listening", "Psychological Assessment", "Empathy & Ethics", "Communication"],
        "professionalCertifications": ["Counsellors and Psychologists Board of Kenya Licensure"],
        "offeringUniversities": [
            {"universityName": "Machakos University", "universityType": "Public", "location": "Machakos", "latestCutoff": 24.615, "previousCutoff": 27.279, "kuccpsCode": "1170337"},
            {"universityName": "Kisii University", "universityType": "Public", "location": "Kisii", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1087337"},
            {"universityName": "Catholic University of Eastern Africa", "universityType": "Private", "location": "Nairobi", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1480337"},
            {"universityName": "KCA University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 22.449, "previousCutoff": 22.916, "kuccpsCode": "1103337"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_bizmgmt",
        "code": "BUS-503",
        "title": "Bachelor of Business Management",
        "faculty": "Business School",
        "minMeanGrade": "C+",
        "averageCutoff": 21.4,
        "clusterGroup": "Cluster 7: Business & Economics",
        "clusterSubjects": ["Mathematics", "English", "Business Studies", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C"},
        "description": "Covers general management, organizational behavior, marketing, and entrepreneurship for business leadership roles.",
        "careerOpportunities": ["Business Manager", "Operations Officer", "Management Trainee", "Entrepreneur"],
        "requiredSkills": ["Strategic Planning", "Financial Literacy", "Leadership", "Communication"],
        "professionalCertifications": ["Kenya Institute of Management (KIM) Certification"],
        "offeringUniversities": [
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 21.375, "previousCutoff": 21.444, "kuccpsCode": "1253151"},
            {"universityName": "University of Eldoret", "universityType": "Public", "location": "Eldoret", "latestCutoff": 21.375, "previousCutoff": 21.444, "kuccpsCode": "1114151"},
            {"universityName": "Co-operative University of Kenya", "universityType": "Public", "location": "Nairobi", "latestCutoff": 21.375, "previousCutoff": 21.444, "kuccpsCode": "1080151"},
            {"universityName": "Kisii University", "universityType": "Public", "location": "Kisii", "latestCutoff": 21.375, "previousCutoff": 21.444, "kuccpsCode": "1087151"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_tourism",
        "code": "BUS-504",
        "title": "Bachelor of Tourism Management",
        "faculty": "School of Tourism and Hospitality Management",
        "minMeanGrade": "C+",
        "averageCutoff": 24.0,
        "clusterGroup": "Cluster 11: Tourism & Hospitality Management",
        "clusterSubjects": ["English", "Kiswahili", "Geography", "Business Studies"],
        "minimumSubjectRequirements": {"English": "C+"},
        "description": "Covers destination marketing, tour operations, travel logistics, and sustainable tourism development.",
        "careerOpportunities": ["Tourism Officer", "Travel Consultant", "Destination Marketing Manager", "Tour Operations Manager"],
        "requiredSkills": ["Customer Service", "Destination Marketing", "Itinerary Planning", "Communication"],
        "professionalCertifications": ["Tourism Regulatory Authority (TRA) Registration"],
        "offeringUniversities": [
            {"universityName": "Maasai Mara University", "universityType": "Public", "location": "Narok", "latestCutoff": 25.915, "previousCutoff": 27.905, "kuccpsCode": "1165157"},
            {"universityName": "Chuka University", "universityType": "Public", "location": "Chuka", "latestCutoff": 24.284, "previousCutoff": 26.854, "kuccpsCode": "1105222"},
            {"universityName": "University of Eldoret", "universityType": "Public", "location": "Eldoret", "latestCutoff": 23.155, "previousCutoff": 25.923, "kuccpsCode": "1114157"},
            {"universityName": "Rongo University", "universityType": "Public", "location": "Rongo", "latestCutoff": 22.806, "previousCutoff": 24.248, "kuccpsCode": "1073157"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_hospitality",
        "code": "BUS-505",
        "title": "Bachelor of Science in Hospitality Management",
        "faculty": "School of Tourism and Hospitality Management",
        "minMeanGrade": "C+",
        "averageCutoff": 21.4,
        "clusterGroup": "Cluster 11: Tourism & Hospitality Management",
        "clusterSubjects": ["English", "Kiswahili", "Geography", "Business Studies"],
        "minimumSubjectRequirements": {"English": "C+"},
        "description": "Covers hotel operations, guest relations, food and beverage management, and hospitality service standards.",
        "careerOpportunities": ["Hotel Manager", "Guest Relations Manager", "Events Coordinator", "Food & Beverage Manager"],
        "requiredSkills": ["Guest Relations", "Operations Management", "Hospitality Service Standards", "Leadership"],
        "professionalCertifications": ["Tourism Regulatory Authority (TRA) Registration"],
        # Only one university in the official KUCCPS list has actual recent
        # cutoff data for this exact degree title - the others offering it
        # ("-" in the source) are omitted rather than shown with invented numbers.
        "offeringUniversities": [
            {"universityName": "Murang'a University of Technology", "universityType": "Public", "location": "Murang'a", "latestCutoff": 21.375, "previousCutoff": 24.429, "kuccpsCode": "1246821"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_realestate",
        "code": "BE-306",
        "title": "Bachelor of Science in Real Estate Management",
        "faculty": "School of the Built Environment",
        "minMeanGrade": "C+",
        "averageCutoff": 18.4,
        "clusterGroup": "Cluster 4: Built Environment & Geosciences",
        "clusterSubjects": ["Mathematics", "Physics", "English", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C+"},
        "description": "Covers property valuation, real estate investment analysis, facilities management, and land economics.",
        "careerOpportunities": ["Real Estate Manager", "Property Valuer", "Facilities Manager", "Estate Agent"],
        "requiredSkills": ["Property Valuation", "Market Analysis", "Negotiation", "Facilities Management"],
        "professionalCertifications": ["Estate Agents Registration Board (EARB) Licensure", "Institution of Surveyors of Kenya (ISK) Membership"],
        # Only one university in the official KUCCPS list has actual recent
        # cutoff data for this exact degree title.
        "offeringUniversities": [
            {"universityName": "Mount Kenya University", "universityType": "Private", "location": "Thika", "latestCutoff": 18.392, "previousCutoff": 18.692, "kuccpsCode": "1279683"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_chemeng",
        "code": "ENG-306",
        "title": "Bachelor of Engineering in Chemical Engineering",
        "faculty": "School of Engineering Sciences",
        "minMeanGrade": "C+",
        "averageCutoff": 35.5,
        "clusterGroup": "Cluster 5: Engineering & Technology",
        "clusterSubjects": ["Mathematics", "Physics", "Chemistry", "English"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+", "Chemistry": "C+", "English": "C+"},
        "description": "Covers chemical process design, plant operations, reaction engineering, and industrial process safety.",
        "careerOpportunities": ["Chemical Process Engineer", "Petrochemical Engineer", "Manufacturing Engineer", "Environmental Engineer"],
        "requiredSkills": ["Process Design", "Chemical Analysis", "Plant Operations", "Problem Solving"],
        "professionalCertifications": ["Engineers Board of Kenya (EBK) Registration"],
        "offeringUniversities": [
            {"universityName": "Technical University of Kenya", "universityType": "Public", "location": "Nairobi", "latestCutoff": 38.978, "previousCutoff": 38.404, "kuccpsCode": "1112599"},
            {"universityName": "Moi University", "universityType": "Public", "location": "Eldoret", "latestCutoff": 34.111, "previousCutoff": 31.769, "kuccpsCode": "1253599"},
            {"universityName": "Dedan Kimathi University of Technology", "universityType": "Public", "location": "Nyeri", "latestCutoff": 33.421, "previousCutoff": 31.644, "kuccpsCode": "1173599"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_hrm",
        "code": "BUS-506",
        "title": "Bachelor of Science in Human Resource Management",
        "faculty": "Business School",
        "minMeanGrade": "C+",
        "averageCutoff": 25.8,
        "clusterGroup": "Cluster 7: Business & Economics",
        "clusterSubjects": ["English", "Kiswahili", "Business Studies", "Mathematics"],
        "minimumSubjectRequirements": {"English": "C+"},
        "description": "Covers recruitment, employee relations, performance management, and organizational development.",
        "careerOpportunities": ["Human Resource Officer", "Talent Acquisition Specialist", "Training & Development Officer", "HR Business Partner"],
        "requiredSkills": ["Recruitment & Selection", "Employee Relations", "Performance Management", "Communication"],
        "professionalCertifications": ["Institute of Human Resource Management (IHRM) Kenya Certification"],
        "offeringUniversities": [
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 29.685, "previousCutoff": 30.688, "kuccpsCode": "1249189"},
            {"universityName": "Maseno University", "universityType": "Public", "location": "Kisumu", "latestCutoff": 27.266, "previousCutoff": 28.744, "kuccpsCode": "1229189"},
            {"universityName": "Meru University of Science and Technology", "universityType": "Public", "location": "Meru", "latestCutoff": 23.523, "previousCutoff": 26.819, "kuccpsCode": "1240189"},
            {"universityName": "Rongo University", "universityType": "Public", "location": "Rongo", "latestCutoff": 22.86, "previousCutoff": 25.574, "kuccpsCode": "1073189"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_intlbiz",
        "code": "BUS-507",
        "title": "Bachelor of Science in International Business Management",
        "faculty": "Business School",
        "minMeanGrade": "C+",
        "averageCutoff": 21.4,
        "clusterGroup": "Cluster 7: Business & Economics",
        "clusterSubjects": ["Mathematics", "English", "Business Studies", "Geography"],
        "minimumSubjectRequirements": {"Mathematics": "C"},
        "description": "Covers international trade theory, global market entry strategy, cross-cultural management, and export/import logistics.",
        "careerOpportunities": ["International Trade Officer", "Export/Import Manager", "Global Business Analyst", "Supply Chain Coordinator"],
        "requiredSkills": ["Cross-Cultural Communication", "Trade Finance", "Market Entry Strategy", "Negotiation"],
        "professionalCertifications": ["Kenya International Freight and Warehousing Association (KIFWA) Affiliation"],
        # Only two universities in the official KUCCPS list have actual
        # recent cutoff data for this exact degree title.
        "offeringUniversities": [
            {"universityName": "Africa Nazarene University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 21.375, "previousCutoff": 21.444, "kuccpsCode": "1078647"},
            {"universityName": "KCA University", "universityType": "Private", "location": "Nairobi", "latestCutoff": 21.375, "previousCutoff": 21.444, "kuccpsCode": "1103647"},
        ],
        "durationYears": 4,
    },
    {
        "id": "prog_urbanplan",
        "code": "BE-307",
        "title": "Bachelor of Urban and Regional Planning",
        "faculty": "School of the Built Environment",
        "minMeanGrade": "C+",
        "averageCutoff": 18.4,
        "clusterGroup": "Cluster 4: Built Environment & Geosciences",
        "clusterSubjects": ["Mathematics", "English", "Geography", "Physics"],
        "minimumSubjectRequirements": {"Mathematics": "C", "English": "C+", "Geography": "C"},
        "description": "Covers land-use planning, urban design, infrastructure policy, and GIS-based spatial analysis for city and regional development.",
        "careerOpportunities": ["Urban Planner", "Regional Development Officer", "GIS Planning Analyst", "County Planning Officer"],
        "requiredSkills": ["Land Use Planning", "GIS Mapping", "Policy Analysis", "Community Engagement"],
        "professionalCertifications": ["Physical and Land Use Planners Registration Board Licensure"],
        # Only two universities in the official KUCCPS list have actual
        # recent cutoff data for this exact degree title.
        "offeringUniversities": [
            {"universityName": "Maasai Mara University", "universityType": "Public", "location": "Narok", "latestCutoff": 18.392, "previousCutoff": 18.692, "kuccpsCode": "1165340"},
            {"universityName": "Maseno University", "universityType": "Public", "location": "Kisumu", "latestCutoff": 18.392, "previousCutoff": 18.692, "kuccpsCode": "1229765"},
        ],
        "durationYears": 5,
    },
    {
        "id": "prog_geomatics",
        "code": "BE-308",
        "title": "Bachelor of Science in Geomatics and Geospatial Information Systems",
        "faculty": "School of the Built Environment",
        "minMeanGrade": "C+",
        "averageCutoff": 21.6,
        "clusterGroup": "Cluster 4: Built Environment & Geosciences",
        "clusterSubjects": ["Mathematics", "Physics", "Geography", "Chemistry"],
        "minimumSubjectRequirements": {"Mathematics": "C+", "Physics": "C+", "Geography": "C"},
        "description": "Covers land surveying, remote sensing, cartography, and GIS-based spatial data analysis for land administration and infrastructure.",
        "careerOpportunities": ["Land Surveyor", "GIS Analyst", "Remote Sensing Specialist", "Cartographer"],
        "requiredSkills": ["GIS Software (ArcGIS/QGIS)", "Land Surveying", "Remote Sensing", "Spatial Data Analysis"],
        "professionalCertifications": ["Institution of Surveyors of Kenya (ISK) Membership", "Survey Board of Kenya Licensure"],
        "offeringUniversities": [
            {"universityName": "Jomo Kenyatta University (JKUAT)", "universityType": "Public", "location": "Juja", "latestCutoff": 33.464, "previousCutoff": 29.483, "kuccpsCode": "1249619"},
            {"universityName": "Dedan Kimathi University of Technology", "universityType": "Public", "location": "Nyeri", "latestCutoff": 15.683, "previousCutoff": 32.149, "kuccpsCode": "1173619"},
            {"universityName": "Taita Taveta University", "universityType": "Public", "location": "Voi", "latestCutoff": 15.683, "previousCutoff": 17.363, "kuccpsCode": "1091619"},
        ],
        "durationYears": 4,
    },
]

PROGRAMME_TITLES: List[str] = [p["title"] for p in PROGRAMMES]
CATALOG_BY_TITLE: Dict[str, Programme] = {p["title"]: p for p in PROGRAMMES}
CATALOG_BY_ID: Dict[str, Programme] = {p["id"]: p for p in PROGRAMMES}
