name: uniguide_mobile
description: "UniGuide: A Random Forest-Based Decision Support System for University Degree Programme Recommendation Among Kenyan Form-Four Leavers (Strathmore University ICS 4A Project by Fatuma Omar Marsa 159056)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.66.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
